### ISSUE TITLE
Error HA Core 2024.5.0

### ISSUE THREAD

**Issue by MarioniK** [onlyoneme/home-assistant-custom-components-wiim#18]
Регистратор: homeassistant.setup
Источник: setup.py:481
Первое сообщение: 08:52:50 (1 сообщений)
Последнее сообщение: 08:52:50

Unable to prepare setup for platform 'wiim_custom.media_player': Unable to set up component.

Error during setup of component wiim_custom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wiim_custom/__init__.py", line 82, in setup
    hass.services.async_register(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2522, in async_register
    self._hass.verify_event_loop_thread("async_register")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'wiim_custom' calls async_register from a thread at custom_components/wiim_custom/__init__.py, line 82: hass.services.async_register(. Please report it to the author of the 'wiim_custom' custom integration.

**Comment by rohrsh** [comment]
Same message for me today

**Comment by JasonOggy** [comment]
as it is for me.

**Comment by dablanco83** [comment]
Yep. Same here.

**Comment by onlyoneme** [comment]
Should be ok now, please use the latest beta branch code.

**Comment by MarioniK** [comment]
> Should be ok now, please use the latest beta branch code.

Thanks, it's working. ))

**Comment by dablanco83** [comment]
Hmm… must be doing something wrong.

1. Uninstalled the WiiM Devices hacs integration.
2.Restart
3. Re-installed 0.36beta via HACS store.
4. Restart

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:190
First occurred: 11:26:21 (3 occurrences)
Last logged: 11:26:38

Detected that custom integration 'wiim_custom' calls async_register from a thread at custom_components/wiim_custom/__init__.py, line 82: hass.services.async_register(, please report it to the author of the 'wiim_custom' custom integration
Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues

**Comment by mauritsivs** [comment]
> Hmm… must be doing something wrong.
> 
> 1. Uninstalled the WiiM Devices hacs integration.
>    2.Restart
> 2. Re-installed 0.36beta via HACS store.
> 3. Restart
> 
> Logger: homeassistant.helpers.frame Source: helpers/frame.py:190 First occurred: 11:26:21 (3 occurrences) Last logged: 11:26:38
> 
> Detected that custom integration 'wiim_custom' calls async_register from a thread at custom_components/wiim_custom/**init**.py, line 82: hass.services.async_register(, please report it to the author of the 'wiim_custom' custom integration Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues

Same here, reinstalled with Beta 0.3.6, but still not working. whats the correct way of doing this?

**Comment by JasonOggy** [comment]
HACS is the problem. It's installed main version not beta. Do it manually.

**Comment by MJWMJW2** [comment]
> > Hmm… must be doing something wrong.
> > 
> > 1. Uninstalled the WiiM Devices hacs integration.
> >    2.Restart
> > 2. Re-installed 0.36beta via HACS store.
> > 3. Restart
> > 
> > Logger: homeassistant.helpers.frame Source: helpers/frame.py:190 First occurred: 11:26:21 (3 occurrences) Last logged: 11:26:38
> > Detected that custom integration 'wiim_custom' calls async_register from a thread at custom_components/wiim_custom/**init**.py, line 82: hass.services.async_register(, please report it to the author of the 'wiim_custom' custom integration Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
> 
> Same here, reinstalled with Beta 0.3.6, but still not working. whats the correct way of doing this?

I am not sure the 'correct' way, but this is how I did it,
Go to https://github.com/onlyoneme/home-assistant-custom-components-wiim/tree/beta/custom_components/wiim_custom
Download the __init__.py and save this to your config/custom_components/wiimm_custom/ replacing the original.
Restart HA.  Now it should work.
